"""Convention and panel views split by domain."""

from .admin import (
    ADMIN_PANEL_SECTIONS,
    admin_panel,
    manage_convention_items,
    randomize_tag_colors,
)
from .auth import login_view, logout_view, register_view
from .conventions import (
    convention_create,
    convention_delete,
    convention_detail,
    convention_edit,
    convention_ical_feed,
)
from .csv import (
    download_hosts_template,
    download_rooms_template,
    download_tags_template,
    export_panels_csv,
    import_hosts_csv,
    import_panels_csv,
    import_rooms_csv,
    import_tags_csv,
)
from .hosts import (
    add_panel_host_ajax,
    delete_host_ajax,
    get_admin_hosts_ajax,
    get_all_hosts_ajax,
    get_host_details_ajax,
    get_hosts_batch_ajax,
    host_edit,
)
from .panels import (
    panel_calendar,
    panel_create,
    panel_delete,
    panel_detail_modal_view,
    panel_edit,
    reorder_hosts_ajax,
    reorder_tags_ajax,
    toggle_cancelled,
)
from .rooms import delete_room_ajax, get_all_rooms_ajax, get_room_details_ajax, save_room_ajax
from .schedule import privacy_policy, schedule
from .tags import (
    add_tag_ajax,
    delete_tag_ajax,
    get_all_tags_ajax,
    get_tag_details_ajax,
    tag_delete,
    tag_edit,
)

__all__ = [
    'ADMIN_PANEL_SECTIONS',
    'add_panel_host_ajax',
    'add_tag_ajax',
    'admin_panel',
    'convention_create',
    'convention_delete',
    'convention_detail',
    'convention_edit',
    'convention_ical_feed',
    'delete_host_ajax',
    'delete_room_ajax',
    'delete_tag_ajax',
    'download_hosts_template',
    'download_rooms_template',
    'download_tags_template',
    'export_panels_csv',
    'get_admin_hosts_ajax',
    'get_all_hosts_ajax',
    'get_all_rooms_ajax',
    'get_all_tags_ajax',
    'get_host_details_ajax',
    'get_hosts_batch_ajax',
    'get_room_details_ajax',
    'get_tag_details_ajax',
    'host_edit',
    'import_hosts_csv',
    'import_panels_csv',
    'import_rooms_csv',
    'import_tags_csv',
    'login_view',
    'logout_view',
    'manage_convention_items',
    'panel_calendar',
    'panel_create',
    'panel_delete',
    'panel_detail_modal_view',
    'panel_edit',
    'privacy_policy',
    'randomize_tag_colors',
    'register_view',
    'reorder_hosts_ajax',
    'reorder_tags_ajax',
    'save_room_ajax',
    'schedule',
    'tag_delete',
    'tag_edit',
    'toggle_cancelled',
]
