"""
Django settings for FurConnectApp project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os
import sys

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Version string for display in footer
try:
    from FurConnectApp import __version__
    from FurConnectApp.version_info import resolve_version_string

    FURCONNECT_VERSION = resolve_version_string(BASE_DIR, __version__)
except ImportError:
    FURCONNECT_VERSION = "dev"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

_hosts = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in _hosts.split(',') if host.strip()]
ALLOWED_HOSTS += ['127.0.0.1', 'localhost']


def _csrf_trusted_origins(hosts, *, allow_http=False):
    """Build exact CSRF trusted origins from hostnames (Django does not support wildcards)."""
    origins = []
    for host in hosts:
        if host.startswith('http://') or host.startswith('https://'):
            origins.append(host.rstrip('/'))
            continue
        if allow_http or host in {'127.0.0.1', 'localhost'}:
            origins.extend([
                f'http://{host}',
                f'http://{host}:8000',
            ])
        origins.append(f'https://{host}')
    return list(dict.fromkeys(origins))


# CSRF Settings
_allow_insecure_cookies = os.environ.get('ALLOW_INSECURE_COOKIES', 'False') == 'True'
_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')

if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip().rstrip('/')
        for origin in _csrf_origins.split(',')
        if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins(
        ALLOWED_HOSTS,
        allow_http=DEBUG or _allow_insecure_cookies,
    )

if DEBUG or _allow_insecure_cookies:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_USE_SESSIONS = False
    SESSION_SAVE_EVERY_REQUEST = True
    USE_X_FORWARDED_HOST = False
    USE_X_FORWARDED_PORT = False
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_USE_SESSIONS = True

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Session Settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events.apps.EventsConfig',
    'widget_tweaks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'events.middleware.ConcatOAuthCallbackMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FurConnectApp.urls'

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'FurConnectApp.settings.furconnect_version',
                'events.context_processors.user_exists_processor',
                'events.context_processors.concat_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'FurConnectApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ["DB_HOST"],
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL configuration
LOGIN_URL = 'events:login'
LOGIN_REDIRECT_URL = 'schedule'
LOGOUT_REDIRECT_URL = 'events:login'

# ConCat integration (panel RSVP)
def _parse_concat_role_list(env_value, default=''):
    raw = env_value if env_value is not None else default
    return [role.strip() for role in raw.split(',') if role.strip()]


def _parse_concat_product_ids(env_value):
    if not env_value:
        return []
    return [int(value.strip()) for value in env_value.split(',') if value.strip()]


CONCAT_ENABLED = os.environ.get('CONCAT_ENABLED', 'False') == 'True'
CONCAT_API_BASE = os.environ.get('CONCAT_API_BASE', '').rstrip('/')
CONCAT_CLIENT_ID = os.environ.get('CONCAT_CLIENT_ID', '')
CONCAT_CLIENT_SECRET = os.environ.get('CONCAT_CLIENT_SECRET', '')
CONCAT_REDIRECT_URI = os.environ.get('CONCAT_REDIRECT_URI', '')
CONCAT_TOKEN_ENDPOINT = os.environ.get(
    'CONCAT_TOKEN_ENDPOINT',
    f'{CONCAT_API_BASE}/api/oauth/token' if CONCAT_API_BASE else '',
)
CONCAT_API_V0_BASE = f'{CONCAT_API_BASE}/api/v0' if CONCAT_API_BASE else ''
CONCAT_SERVICE_SCOPES = os.environ.get('CONCAT_SERVICE_SCOPES', 'user:read registration:read')

# ConCat roles that may manage conventions (edit schedule, add panels, etc.).
CONCAT_EVENTS_ROLE = _parse_concat_role_list(os.environ.get('CONCAT_EVENTS_ROLE'), 'events')
CONCAT_MANAGE_ROLES = _parse_concat_role_list(os.environ.get('CONCAT_MANAGE_ROLES'))
if not CONCAT_MANAGE_ROLES and CONCAT_EVENTS_ROLE:
    CONCAT_MANAGE_ROLES = list(CONCAT_EVENTS_ROLE)
# ConCat roles that skip panel RSVP (organizers/events staff).
CONCAT_SKIP_RSVP_ROLES = _parse_concat_role_list(
    os.environ.get('CONCAT_SKIP_RSVP_ROLES'),
    'admin',
)
for role in CONCAT_EVENTS_ROLE:
    if role not in CONCAT_SKIP_RSVP_ROLES:
        CONCAT_SKIP_RSVP_ROLES.append(role)
# Optional: only users with one of these ConCat roles may RSVP (empty = any signed-in user).
CONCAT_RSVP_REQUIRED_ROLES = _parse_concat_role_list(os.environ.get('CONCAT_RSVP_REQUIRED_ROLES'))
# Optional: require paid registration and/or specific badge product IDs (like Discord badge sync).
CONCAT_REQUIRE_PAID_REGISTRATION = os.environ.get('CONCAT_REQUIRE_PAID_REGISTRATION', 'False') == 'True'
CONCAT_RSVP_PRODUCT_IDS = _parse_concat_product_ids(os.environ.get('CONCAT_RSVP_PRODUCT_IDS'))

# Eventzilla integration (panel RSVP via registered attendee email)
EVENTZILLA_ENABLED = os.environ.get('EVENTZILLA_ENABLED', 'False') == 'True'
EVENTZILLA_API_BASE = os.environ.get(
    'EVENTZILLA_API_BASE',
    'https://www.eventzillaapi.net/api/v2',
).rstrip('/')
EVENTZILLA_API_KEY = os.environ.get('EVENTZILLA_API_KEY', '')
EVENTZILLA_EVENT_ID = os.environ.get('EVENTZILLA_EVENT_ID', '')
EVENTZILLA_REQUIRE_PAID_REGISTRATION = (
    os.environ.get('EVENTZILLA_REQUIRE_PAID_REGISTRATION', 'True') == 'True'
)
EVENTZILLA_ALLOWED_TICKET_TYPES = [
    ticket.strip()
    for ticket in os.environ.get('EVENTZILLA_ALLOWED_TICKET_TYPES', '').split(',')
    if ticket.strip()
]

def furconnect_version(request):
    from django.conf import settings
    return {'FURCONNECT_VERSION': getattr(settings, 'FURCONNECT_VERSION', 'dev')}
